#!/bin/bash
echo "Trying to test VideoInput library with VideoInputTester"
echo "if the files dont run , you may need to execute ./make to compile them for a 32 bit"
echo "the binaries provided are for x64 computers"
VideoInputTester/bin/Release/VideoInputTester
exit 0
